# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='warden',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='st_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='students.Group'),
        ),
    ]
