# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20161212_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(),
        ),
    ]
